title: Santhiya's Blog
author: SRH
email: earthcharmeddec@gmail.com
description: > # this means to ignore newlines until "baseurl:"

baseurl: Blog with Santhiya Holmes resume and other information on development.

(This will appear in your document head meta (for
   Google search results) and in your feed.xml site description)

# social links
twitter_username: N/A
github_username:  earthcharmeddec

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
